"""add holdings_snapshots and dividend_events

Revision ID: 58a9c9456d2e
Revises: b25527bab7ee
Create Date: 2025-11-26 19:36:15.071885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58a9c9456d2e'
down_revision: Union[str, Sequence[str], None] = 'b25527bab7ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holding_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('plaid_account_id', sa.BigInteger(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plaid_account_id', 'as_of_date', name='uq_holding_snapshots_plaid_date')
    )
    op.create_index(op.f('ix_holding_snapshots_as_of_date'), 'holding_snapshots', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_holding_snapshots_plaid_account_id'), 'holding_snapshots', ['plaid_account_id'], unique=False)
    op.create_table('price_quotes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'as_of_date', 'source', name='uq_price_quotes_symbol_date_source')
    )
    op.create_index(op.f('ix_price_quotes_as_of_date'), 'price_quotes', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_price_quotes_symbol'), 'price_quotes', ['symbol'], unique=False)
    op.create_table('dividend_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('plaid_account_id', sa.BigInteger(), nullable=False),
    sa.Column('lm_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('pay_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lm_transaction_id'], ['lm_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dividend_events_lm_transaction_id'), 'dividend_events', ['lm_transaction_id'], unique=False)
    op.create_index(op.f('ix_dividend_events_pay_date'), 'dividend_events', ['pay_date'], unique=False)
    op.create_index(op.f('ix_dividend_events_plaid_account_id'), 'dividend_events', ['plaid_account_id'], unique=False)
    op.create_index(op.f('ix_dividend_events_symbol'), 'dividend_events', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dividend_events_symbol'), table_name='dividend_events')
    op.drop_index(op.f('ix_dividend_events_plaid_account_id'), table_name='dividend_events')
    op.drop_index(op.f('ix_dividend_events_pay_date'), table_name='dividend_events')
    op.drop_index(op.f('ix_dividend_events_lm_transaction_id'), table_name='dividend_events')
    op.drop_table('dividend_events')
    op.drop_index(op.f('ix_price_quotes_symbol'), table_name='price_quotes')
    op.drop_index(op.f('ix_price_quotes_as_of_date'), table_name='price_quotes')
    op.drop_table('price_quotes')
    op.drop_index(op.f('ix_holding_snapshots_plaid_account_id'), table_name='holding_snapshots')
    op.drop_index(op.f('ix_holding_snapshots_as_of_date'), table_name='holding_snapshots')
    op.drop_table('holding_snapshots')
    # ### end Alembic commands ###
