"""init core schema

Revision ID: a8871558150a
Revises: 
Create Date: 2025-11-26 00:21:20.742255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8871558150a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lm_accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('subtype', sa.Text(), nullable=True),
    sa.Column('balance', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_margin', sa.Boolean(), nullable=False),
    sa.Column('is_cash_like', sa.Boolean(), nullable=False),
    sa.Column('is_external_synced', sa.Boolean(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lm_categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_income', sa.Boolean(), nullable=False),
    sa.Column('is_transfer', sa.Boolean(), nullable=False),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(), nullable=False),
    sa.Column('positions_value', sa.Numeric(), nullable=False),
    sa.Column('cash', sa.Numeric(), nullable=False),
    sa.Column('margin_debt', sa.Numeric(), nullable=False),
    sa.Column('net_liquidation', sa.Numeric(), nullable=False),
    sa.Column('annual_income', sa.Numeric(), nullable=False),
    sa.Column('monthly_income', sa.Numeric(), nullable=False),
    sa.Column('portfolio_yield', sa.Numeric(), nullable=False),
    sa.Column('margin_pct', sa.Numeric(), nullable=True),
    sa.Column('margin_band', sa.Text(), nullable=True),
    sa.Column('goal_monthly_target', sa.Numeric(), nullable=True),
    sa.Column('goal_progress_pct', sa.Numeric(), nullable=True),
    sa.Column('raw_request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spending_buckets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_fixed', sa.Boolean(), nullable=False),
    sa.Column('priority_level', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_bucket_map',
    sa.Column('lm_category_id', sa.BigInteger(), nullable=False),
    sa.Column('bucket_id', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bucket_id'], ['spending_buckets.id'], ),
    sa.ForeignKeyConstraint(['lm_category_id'], ['lm_categories.id'], ),
    sa.PrimaryKeyConstraint('lm_category_id', 'bucket_id')
    )
    op.create_table('lm_transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('payee', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('is_pending', sa.Boolean(), nullable=False),
    sa.Column('is_income', sa.Boolean(), nullable=False),
    sa.Column('is_transfer', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['lm_accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['lm_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshot_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshot_positions')
    op.drop_table('lm_transactions')
    op.drop_table('category_bucket_map')
    op.drop_table('spending_buckets')
    op.drop_table('snapshots')
    op.drop_table('lm_categories')
    op.drop_table('lm_accounts')
    # ### end Alembic commands ###
