"""add lm_tx_id and plaid_account_id

Revision ID: b25527bab7ee
Revises: a8871558150a
Create Date: 2025-11-26 14:05:21.180954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25527bab7ee'
down_revision: Union[str, Sequence[str], None] = 'a8871558150a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lm_transactions', sa.Column('lm_tx_id', sa.BigInteger(), nullable=False))
    op.add_column('lm_transactions', sa.Column('plaid_account_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_lm_transactions_lm_tx_id'), 'lm_transactions', ['lm_tx_id'], unique=True)
    op.create_index(op.f('ix_lm_transactions_plaid_account_id'), 'lm_transactions', ['plaid_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lm_transactions_plaid_account_id'), table_name='lm_transactions')
    op.drop_index(op.f('ix_lm_transactions_lm_tx_id'), table_name='lm_transactions')
    op.drop_column('lm_transactions', 'plaid_account_id')
    op.drop_column('lm_transactions', 'lm_tx_id')
    # ### end Alembic commands ###
